---
- name: Create Credentials
  hosts: localhost
  gather_facts: no
#  connection: local
  collections:
    - awx.awx
  
  tasks:
    - name: Add tower credential
      tower_credential:
        name: testnew2
        organization: Default
        kind: ssh
        username: admin12
        password: testos
