---
# This isn't mandatory but it is a way to call kinit from within Ansible before calling the lookup
#  - name: call kinit to retrieve Kerberos token
#    expect:
#      command: kinit admin@192.168.0.100
#      responses:
#        (?i)password: redhat
#      no_log: True

#  - name: Get the LAPS password using Kerberos auth, relies on kinit already being called
#    set_fact:
#      ansible_password: "{{ lookup('community.windows.laps_password', '{{ server_name }}', domain='dc01.ansible.com') }}"
  
#  - name: Specific the domain host using an explicit LDAP URI
#    set_fact:
#      ansible_password: "{{ lookup('community.windows.laps_password', '{{ server_name }}', domain='ldap://ansible.com:389') }}"
  
  - name: Use Simple auth over LDAPS
    set_fact:
      ansible_password: "{{ lookup('community.windows.laps_password', '{{ server_name }}',
                                   domain='dc01.ansible.com',
                                   auth='simple',
                                   scheme='ldaps',
                                   username='username@ANSIBLE.COM',
                                   password='SuperSecret123') }}"
  
#  - name: Use Simple auth with LDAP and StartTLS
#    set_fact:
#      ansible_password: "{{ lookup('community.windows.laps_password', '{{ server_name }}',
#                                   domain='dc01.ansible.com',
#                                   auth='simple',
#                                   start_tls=True,
#                                   username='username@ANSIBLE.COM',
#                                   password='SuperSecret123') }}"
#  
#  - name: Narrow down the search base to a an OU
#    set_fact:
#      ansible_password: "{{ lookup('community.windows.laps_password', '{{ server_name }}',
#                                   domain='dc01.ansible.com',
#                                   search_base='OU=Databases,DC=ansible,DC=com') }}"
#  
#  - name: Set certificate file to use when validating the TLS certificate
#    set_fact:
#      ansible_password: "{{ lookup('community.windows.laps_password', {{ server_name }},
#                                   domain='dc01.ansible.com',
#                                   start_tls=True,
#                                   ca_cert='/usr/local/share/certs/ad.pem') }}"r_host, tower_password, tower_username, user, username, validate_certs, vault_id, vault_password",
