---
  - name: Add tower credential
    tower_credential:
      name: Team Name
      description: Team Description
      organization: test-org
      kind: ssh
      state: present
#      tower_config_file: "~/.tower_cli.cfg"
